[package]
name = "rust-brain-teasers"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = ["amnesia","boxes","byte_sized", "out_of_order", "quack", "reboot_universe","standard_input", "string_length", "there_and_back","three_and_a_bit", "type_conversion", "x_marks_spot"]
