[package]
name = "rust-brain-teasers"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = ["byte_sized", "reboot_universe","standard_input", "string_length","three_and_a_bit", "type_conversion"]
